services:
  database:
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5000:5432"
    volumes:
      - ./.docker-compose/database/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: echo 'select 1' | psql -h localhost -U postgres  | grep -q '1 row'
      interval: 3s
      retries: 10
      timeout: 3s
  flyway:
    image: flyway/flyway
    volumes:
      - ./schema/:/flyway/sql
    command: >
      -locations=filesystem:/flyway/sql
      -connectRetries=60
      -user=postgres
      -password=postgres
      -url=jdbc:postgresql://database:5432/wnc_helene_test
      migrate
    depends_on:
      - database
  gradle:
    image: gradle:8.10-jdk23
    build:
      context: ./webapp/gradle
      dockerfile: Dockerfile
    volumes:
      - ./webapp:/app
    working_dir: /app
    command: >
      ./gradlew build bootJar -x composeUp -x composeDown --info
    environment:
      - DB_URL=database:5432
      - WEBHOOK_SECRET=secret
      - DB_NAME=wnc_helene_test
    depends_on:
      flyway:
        condition: service_completed_successfully
  app:
    image: openjdk:23-jdk-slim
    volumes:
      - ./webapp/build/libs/:/build/
    command: >
      java -jar /build/supplies-database.jar
    ports:
      - "8000:8080"
    depends_on:
      gradle:
        condition: service_completed_successfully
    environment:
      - DB_URL=database:5432
      - WEBHOOK_SECRET=secret
      - DB_NAME=wnc_helene_test
